language: php
php:
  - 7.2
  - 7.3
  - 7.4
dist: xenial
services:
  - docker
before_install:
  - docker run -d -p 9000:9000 minio/minio server /data
before_script:
  - composer install --prefer-source --no-interaction
  - composer require phpseclib/phpseclib
script:
  - vendor/bin/phpunit --coverage-clover=clover.xml
after_script:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - php php-coveralls.phar --verbose
cache:
  directories:
    - $HOME/.composer/cache/files